Spring:
  datasource:
    name: shut_blog
    url: jdbc:mysql://localhost:3306/shut_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123!@#
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: self.projects.shutblog.entity

server:
  port: 8081
  servlet:
    context-path: /shutblog
